version: '3'

networks:
  django:

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./src:/src
    command: >
      sh -c 'python manage.py wait_for_db && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000'
    environment:
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=superpassword22
    depends_on:
      - postgres
    container_name: webserver
    networks:
      - django

  postgres:
    image: postgres:10-alpine
    restart: unless-stopped
    tty: true
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=superpassword22
    container_name: postgres
    networks:
      - django
